name: Manual Validation Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (defaults to current)'
        required: false
        default: ''
      mvn_profiles:
        description: 'Maven profiles (comma-separated)'
        required: false
        default: 'zip'
      goals:
        description: 'Maven goals'
        required: false
        default: 'install'
      extra_args:
        description: 'Extra mvn arguments (optional)'
        required: false
        default: ''

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          PROFILES="${{ inputs.mvn_profiles }}"
          GOALS="${{ inputs.goals }}"
          EXTRA="${{ inputs.extra_args }}"
          echo "Running: mvn -P${PROFILES} ${GOALS} ${EXTRA}"
          mvn -P${PROFILES} ${GOALS} ${EXTRA}